# Generated by Django 3.2.14 on 2022-07-30 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('fund_name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Fund name')),
                ('sanction_year', models.DateField(verbose_name='Year')),
                ('balance', models.FloatField(default=0, verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_sr_no', models.CharField(max_length=30, unique=True, verbose_name='Product Serial Number')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('year_of_purchase', models.DateField(verbose_name='Purchase Year')),
                ('LP_NO', models.CharField(max_length=5, verbose_name='LP Number')),
                ('initial_price', models.FloatField(default=0, verbose_name='Initial Price')),
                ('issued_to', models.CharField(max_length=100, verbose_name='Issued To')),
                ('Depreciated_Price', models.FloatField(default=0, verbose_name='Depreciated Price')),
                ('Remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('barcode', models.ImageField(blank=True, default='0', upload_to='barcodes/')),
                ('fund_name', models.ForeignKey(db_column='fund_name', on_delete=django.db.models.deletion.DO_NOTHING, to='home.funds')),
            ],
        ),
    ]
