# Generated by Django 3.2.14 on 2022-07-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_sr_no', models.CharField(max_length=30, verbose_name='Product Serial Number')),
                ('item_name', models.CharField(max_length=200, verbose_name='Item Name')),
                ('year_of_purchase', models.DateField(verbose_name='Year of Purchase')),
                ('fund_name', models.CharField(max_length=200, verbose_name='Fund Name')),
                ('LP_NO', models.CharField(max_length=5, verbose_name='LP Number')),
                ('initial_price', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Initial Price')),
                ('issued_to', models.CharField(max_length=100, verbose_name='Issued To')),
                ('Depreciated_Price', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Depreciated Price')),
                ('Remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
            ],
        ),
    ]
