# Generated by Django 3.2.14 on 2022-08-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Depreciated_Price',
            field=models.CharField(blank=True, max_length=30, verbose_name='Depreciated Price'),
        ),
    ]
