# Generated by Django 3.2.14 on 2022-07-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Depreciated_Price',
            field=models.IntegerField(default=0, verbose_name='Depreciated Price'),
        ),
        migrations.AlterField(
            model_name='items',
            name='initial_price',
            field=models.IntegerField(default=0, verbose_name='Initial Price'),
        ),
    ]
