# Generated by Django 3.2.14 on 2022-07-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220726_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Depreciated_Price',
            field=models.FloatField(default=0, verbose_name='Depreciated Price'),
        ),
        migrations.AlterField(
            model_name='items',
            name='initial_price',
            field=models.FloatField(default=0, verbose_name='Initial Price'),
        ),
    ]
