# Generated by Django 3.2.14 on 2022-07-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220726_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Product_sr_no',
            field=models.CharField(max_length=30, unique=True, verbose_name='Product Serial Number'),
        ),
        migrations.AlterField(
            model_name='items',
            name='barcode',
            field=models.ImageField(blank=True, default='0', upload_to='barcodes/'),
        ),
    ]
