# Generated by Django 3.2.14 on 2022-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220729_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=30, unique=True, verbose_name='Fund name')),
                ('sanction_year', models.DateField(verbose_name='Year')),
                ('balance', models.FloatField(default=0, verbose_name='Balance')),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='year_of_purchase',
            field=models.DateField(verbose_name='Purchase Year'),
        ),
    ]
