# Generated by Django 3.2.14 on 2022-07-29 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220730_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='fund_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.funds'),
        ),
    ]
